### ISSUE TITLE
rGenerator fails when aar dependency changes

### ISSUE THREAD

**Issue by skolberg** [scala-android/sbt-android#259] opened 2016-04-26 07:41 UTC
I have two projects. 

1. Provides a framework in form of a number of libraries, two of which are published as _aars_
2. Is an application project that uses the libraries of the first project.

Now, whenever I change something in one of my framework _aars_ and then build my application withhout a call to _clean_ first. I get the error message:

`
/android:rGenerator) Return code 1 for process '/usr/local/opt/android-sdk/build-tools/23.0.2/aapt package -f --no-crunch -I /usr/local/opt/android-sdk/platforms/android-19/android.jar 
-M [app path]/target/android/intermediates/manifest/AndroidManifest.xml 
-S [app path]/target/android/intermediates/res 
-A [app path]/target/android/intermediates/assets -m 
-J [app path]/target/android/generated/source 
-G [app path]/target/android/intermediates/proguard/proguard.txt 
--debug-mode --custom-package [my package] -0 apk --output-text-symbols [app path]/target/android/generated/source --no-version-vectors'
`

Tried with versions from _android-sdk-plugin_ _1.5.15_, _android-sdk-plugin_ _1.6.0_ and _sbt-android 1.6.1-SNAPSHOT_

I did a couple of things to track the issue, but got stuck at some point. So: 

Right before the error I can see the following log output:

`[info] Unpacking aar: [my library aar]-0.xx.x-SNAPSHOT`
`[info] Collecting resources`
`[info] Performing incremental resource merge`
`[info] Processing resources`
`...`
`[warn]  .../AndroidManifest.xml:23: error: Error: No resource found that matches the given name (at 'theme' with value '@style/AppTheme')
`
Where `@style/AppTheme` is defined in my library aar.

* timstamps in _target/android/intermediates/aars_ have all been updated
* exploded aar timestamp in ~/.android/sbt/exploded_aars/_ has been updated
* _target/android/intermediates/res_ is empty

I suspect that in _resources.scala_ around line 121 the res folder is emptied. But I fail to figure out where it should be filled properly again.

**Comment by skolberg** [comment] 2016-04-26 07:57
Another note:

I am able to force a full resource merge by changing _line 148_ of _resources.scala_ to:

`    } else if (!merger.checkValidUpdate(resources.asJava) || Option(resTarget.list()).forall(_.isEmpty)) {`

It works. However, to me this feels more like a workaround.

**Comment by pfn** [comment] 2016-04-26 13:52
Needs more info:

Is this a multiproject build or two completely separate projects?

What exactly is the sequence of commands?

Please provide a reproduction case.

**Comment by skolberg** [comment] 2016-04-26 14:07
Well, I'm afraid I cannot provide a reproduction case immediately, but I think the setup is not that fancy, so here are some more infos:

Both projects are MultiProjects with _XXXBuild.scala_ build scripts. Neither uses _AutoPlugin_ or _AutoBuild_.

I create the library _aar_ with `publishLocal` in **project one**.

Settings:

 `.settings(androidBuildAar: _*)`

The library is packaged and published to my local ivy successfully.

In **project two** I have two simple non-Android libraries and one Android Application

I run `android:packageDebug` or `android:run`, (both leading to the same error.

APK module Settings:

`.settings(androidBuild: _*)`

I add an apk artifact for `publish` and `publishLocal` with

`.settings(addArtifact(Artifact("[my app]", "apk", "apk"), packageDebug in Android): _*)`

I may be able to setup a simple reproduction scenario during one of the next weekends.

**Comment by pfn** [comment] 2016-04-26 14:22
Presumably, this does not occur when you bump your aar versions?

**Comment by skolberg** [comment] 2016-04-26 14:25
Correct, though the library is published locally as _SNAPSHOT_.

**Comment by pfn** [comment] 2016-04-26 16:19
> Another note:
> 
> I am able to force a full resource merge by changing line 148 of resources.scala to:
> 
> } else if (!merger.checkValidUpdate(resources.asJava) || Option(resTarget.list()).forall(_.isEmpty)) {
> 
> It works. However, to me this feels more like a workaround.

Seems reasonable enough, please submit a PR. A full merge is required as the merged resources have been deleted (invalidated) due to the changed AAR.

Perhaps, instead of always requiring a full merge when resTarget is empty, set a full-merge var in the nuke-res-if-changed block and change the signature of incrResourceMerge to accept the value, and call fullResourceMerge if the value is set.

Either way, submit a PR and it should be ok.

**Comment by skolberg** [comment] 2016-04-27 07:36
done

**Closed** 2016-04-28 03:14 UTC
